const ADD_FRIEND = 'ADD_FRIEND',
    STAR_FRIEND = 'STAR_FRIEND',
    DELETE_FRIEND = 'DELETE_FRIEND',
    FETCH_REQUEST = 'FETCH_REQUEST',
    FETCH_ERROR = 'FETCH_ERROR',
    FETCH_SUCCESS = 'FETCH_SUCCESS';

export {ADD_FRIEND, DELETE_FRIEND, STAR_FRIEND, FETCH_REQUEST, FETCH_ERROR, FETCH_SUCCESS};